name: 掘金自动签到
on:
  schedule:
    # `分 时 天 月 周` 时按照标准时间 北京时间=标准时间+8 18表示北京时间早上2点
    # - cron: '0 18 * * *'
    - cron: '45 8 * * *'
jobs:
  check_in:
    runs-on: ubuntu-latest
    steps:
      # 使用 node:10
      - name: 使用 Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: 10

      # npm install
      - name: npm install
        run: |
          npm install
        env:
          CI: true

      # 运行脚本
      - name: 运行脚本
        run: |
          COOKIE='${{ secrets.COOKIE }}' npm start
        env:
          CI: true
